'use client';
import * as LucideIcons from 'lucide-react';

const createWrapper = (IconComponent: any) => {
  return function IconWrapper(props: any) {
    if (!IconComponent) return null;
    return <IconComponent {...props} />;
  };
};

export const Users = createWrapper(LucideIcons.Users);
export const User = createWrapper(LucideIcons.User);
export const SearchX = createWrapper(LucideIcons.SearchX);
export const Search = createWrapper(LucideIcons.Search);
export const Star = createWrapper(LucideIcons.Star);
export const ArrowLeft = createWrapper(LucideIcons.ArrowLeft);
export const Heart = createWrapper(LucideIcons.Heart);
export const History = createWrapper(LucideIcons.History);
export const CheckCircle = createWrapper(LucideIcons.CheckCircle);
export const MapPin = createWrapper(LucideIcons.MapPin);
export const MessageSquare = createWrapper(LucideIcons.MessageSquare);
export const Shield = createWrapper(LucideIcons.Shield);
export const Activity = createWrapper(LucideIcons.Activity);
export const Calendar = createWrapper(LucideIcons.Calendar);
export const Settings = createWrapper(LucideIcons.Settings);
export const LogOut = createWrapper(LucideIcons.LogOut);
export const Check = createWrapper(LucideIcons.Check);
export const X = createWrapper(LucideIcons.X);
export const AlertCircle = createWrapper(LucideIcons.AlertCircle);
export const Image = createWrapper(LucideIcons.Image);
export const ImageIcon = Image;
export const Camera = createWrapper(LucideIcons.Camera);
export const Phone = createWrapper(LucideIcons.Phone);
export const Menu = createWrapper(LucideIcons.Menu);
export const Share2 = createWrapper(LucideIcons.Share2);
export const Trophy = createWrapper(LucideIcons.Trophy);
export const Bell = createWrapper(LucideIcons.Bell);
export const Home = createWrapper(LucideIcons.Home);
export const UserX = createWrapper(LucideIcons.UserX);
export const ShieldCheck = createWrapper(LucideIcons.ShieldCheck);
export const GraduationCap = createWrapper(LucideIcons.GraduationCap);
export const Info = createWrapper(LucideIcons.Info);
export const Mail = createWrapper(LucideIcons.Mail);
export const CreditCard = createWrapper(LucideIcons.CreditCard);
export const Loader2 = createWrapper(LucideIcons.Loader2);
export const Send = createWrapper(LucideIcons.Send);
export const Smartphone = createWrapper(LucideIcons.Smartphone);
export const MessageCircle = createWrapper(LucideIcons.MessageCircle);
export const Bookmark = createWrapper(LucideIcons.Bookmark);
export const EyeOff = createWrapper(LucideIcons.EyeOff);
export const Ban = createWrapper(LucideIcons.Ban);
export const ChevronRight = createWrapper(LucideIcons.ChevronRight);
export const CheckCircle2 = createWrapper(LucideIcons.CheckCircle2);
export const Save = createWrapper(LucideIcons.Save);
export const Filter = createWrapper(LucideIcons.Filter);
export const Lock = createWrapper(LucideIcons.Lock);
export const UserRound = createWrapper(LucideIcons.UserRound);
export const PartyPopper = createWrapper(LucideIcons.PartyPopper);
export const ChevronLeft = createWrapper(LucideIcons.ChevronLeft);
export const ShieldAlert = createWrapper(LucideIcons.ShieldAlert);
