'use client';
export function Search(props: any) { return <span {...props}>Icon</span>; }
export function Star(props: any) { return <span {...props}>Icon</span>; }
export function Users(props: any) { return <span {...props}>Icon</span>; }
export function ArrowLeft(props: any) { return <span {...props}>Icon</span>; }
export function User(props: any) { return <span {...props}>Icon</span>; }
export function Heart(props: any) { return <span {...props}>Icon</span>; }
export function ImageIcon(props: any) { return <span {...props}>Icon</span>; }
export function Image(props: any) { return <span {...props}>Icon</span>; }
export function History(props: any) { return <span {...props}>Icon</span>; }
export function UserX(props: any) { return <span {...props}>Icon</span>; }
export function UserMinus(props: any) { return <span {...props}>Icon</span>; }
export function SearchX(props: any) { return <span {...props}>Icon</span>; }
export function Loader2(props: any) { return <span {...props}>Icon</span>; }
export function Filter(props: any) { return <span {...props}>Icon</span>; }
export function Phone(props: any) { return <span {...props}>Icon</span>; }
export function Mail(props: any) { return <span {...props}>Icon</span>; }
export function MapPin(props: any) { return <span {...props}>Icon</span>; }
export function CheckCircle2(props: any) { return <span {...props}>Icon</span>; }
export function ChevronRight(props: any) { return <span {...props}>Icon</span>; }
export function Save(props: any) { return <span {...props}>Icon</span>; }
export function Info(props: any) { return <span {...props}>Icon</span>; }
export function Shield(props: any) { return <span {...props}>Icon</span>; }
export function Activity(props: any) { return <span {...props}>Icon</span>; }
export function GraduationCap(props: any) { return <span {...props}>Icon</span>; }
export function MessageCircle(props: any) { return <span {...props}>Icon</span>; }
export function Ban(props: any) { return <span {...props}>Icon</span>; }
export function Bookmark(props: any) { return <span {...props}>Icon</span>; }
export function EyeOff(props: any) { return <span {...props}>Icon</span>; }
export function ShieldAlert(props: any) { return <span {...props}>Icon</span>; }
export function Send(props: any) { return <span {...props}>Icon</span>; }
export function Check(props: any) { return <span {...props}>Icon</span>; }
export function X(props: any) { return <span {...props}>Icon</span>; }
export function CreditCard(props: any) { return <span {...props}>Icon</span>; }
export function CheckCircle(props: any) { return <span {...props}>Icon</span>; }
export function Smartphone(props: any) { return <span {...props}>Icon</span>; }
export function Trophy(props: any) { return <span {...props}>Icon</span>; }
export function ShieldCheck(props: any) { return <span {...props}>Icon</span>; }
export function UserRound(props: any) { return <span {...props}>Icon</span>; }
export function PartyPopper(props: any) { return <span {...props}>Icon</span>; }
export function ChevronLeft(props: any) { return <span {...props}>Icon</span>; }
export function Bell(props: any) { return <span {...props}>Icon</span>; }
export function Home(props: any) { return <span {...props}>Icon</span>; }
export function Menu(props: any) { return <span {...props}>Icon</span>; }
export function Calendar(props: any) { return <span {...props}>Icon</span>; }
export function Settings(props: any) { return <span {...props}>Icon</span>; }
export function LogOut(props: any) { return <span {...props}>Icon</span>; }
export function Lock(props: any) { return <span {...props}>Icon</span>; }
export function Share2(props: any) { return <span {...props}>Icon</span>; }
